// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"com.softwarethree/IndividualProject/utilities"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitSummary(messagePhrase string) utilities.AccountSummary {
	account := utilities.ProvideAccount()
	accountSummary := utilities.ProvideAccountSummary(account, messagePhrase)
	return accountSummary
}

func InitEncryption() utilities.Encrypt {
	encrypt := utilities.ProvideEncryptor()
	return encrypt
}

// wire.go:

// InitTestAccount injector
func InitTestAccount() utilities.Account {
	testAccount := utilities.ProvideTestAccount()
	return testAccount
}

var EncryptSet = wire.NewSet(utilities.ProvideEncrypt, wire.Bind((*utilities.Encryption)(nil), (*utilities.Encrypt)(nil)), utilities.ProvideEncryptor)
